//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriptionsInfrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubscriptionsInfrastructure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PlanId is either missing or invalid.
        /// </summary>
        internal static string ChangeSubscriptionPlanRequestValidator_InvalidPlanId {
            get {
                return ResourceManager.GetString("ChangeSubscriptionPlanRequestValidator_InvalidPlanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProviderName is either missing or invalid.
        /// </summary>
        internal static string MigrateSubscriptionRequestValidator_InvalidProviderName {
            get {
                return ResourceManager.GetString("MigrateSubscriptionRequestValidator_InvalidProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProviderState is empty, and must contain some state.
        /// </summary>
        internal static string MigrateSubscriptionRequestValidator_InvalidProviderState {
            get {
                return ResourceManager.GetString("MigrateSubscriptionRequestValidator_InvalidProviderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FromUtc is after the ToUtc.
        /// </summary>
        internal static string SearchSubscriptionHistoryRequestValidator_FromUtc_StartAfterEnd {
            get {
                return ResourceManager.GetString("SearchSubscriptionHistoryRequestValidator_FromUtc_StartAfterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FromUtc is too far in the future, only dates before &apos;{0:yyyy-MM-dd} UTC&apos; are permitted.
        /// </summary>
        internal static string SearchSubscriptionHistoryRequestValidator_FromUtc_TooFuture {
            get {
                return ResourceManager.GetString("SearchSubscriptionHistoryRequestValidator_FromUtc_TooFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FromUtc is too far in the past, only dates after &apos;{0:yyyy-MM-dd} UTC&apos; are permitted.
        /// </summary>
        internal static string SearchSubscriptionHistoryRequestValidator_FromUtc_TooPast {
            get {
                return ResourceManager.GetString("SearchSubscriptionHistoryRequestValidator_FromUtc_TooPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ToUtc is before the FromUtc.
        /// </summary>
        internal static string SearchSubscriptionHistoryRequestValidator_ToUtc_EndBeforeStart {
            get {
                return ResourceManager.GetString("SearchSubscriptionHistoryRequestValidator_ToUtc_EndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ToUtc is too far in the future, only dates before &apos;{0:yyyy-MM-dd} UTC&apos; are permitted.
        /// </summary>
        internal static string SearchSubscriptionHistoryRequestValidator_ToUtc_TooFuture {
            get {
                return ResourceManager.GetString("SearchSubscriptionHistoryRequestValidator_ToUtc_TooFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ToUtc is too far in the past, only dates after &apos;{0:yyyy-MM-dd} UTC&apos; are permitted.
        /// </summary>
        internal static string SearchSubscriptionHistoryRequestValidator_ToUtc_TooPast {
            get {
                return ResourceManager.GetString("SearchSubscriptionHistoryRequestValidator_ToUtc_TooPast", resourceCulture);
            }
        }
    }
}
