//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Web.Hosting.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Web.Hosting.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed APIKEY authentication.
        /// </summary>
        internal static string APIKeyAuthenticationHandler_FailedAuthentication {
            get {
                return ResourceManager.GetString("APIKeyAuthenticationHandler_FailedAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a value in the &apos;{0}&apos; parameter of the request.
        /// </summary>
        internal static string APIKeyAuthenticationHandler_MissingParameter {
            get {
                return ResourceManager.GetString("APIKeyAuthenticationHandler_MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string AuthenticationHandler_Failed {
            get {
                return ResourceManager.GetString("AuthenticationHandler_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires HTTPS.
        /// </summary>
        internal static string AuthenticationHandler_NotHttps {
            get {
                return ResourceManager.GetString("AuthenticationHandler_NotHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is misconfigured: Missing a valid value for the setting {0}.
        /// </summary>
        internal static string CORS_MissingSameOrigins {
            get {
                return ResourceManager.GetString("CORS_MissingSameOrigins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to AES encrypt the user ID.
        /// </summary>
        internal static string CSFRTokenPair_FailedEncryptUserId {
            get {
                return ResourceManager.GetString("CSFRTokenPair_FailedEncryptUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Host of the base URL could not be determined from: &apos;{0}&apos;.
        /// </summary>
        internal static string CSRFMiddleware_InvalidHostName {
            get {
                return ResourceManager.GetString("CSRFMiddleware_InvalidHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSRF cookie and/or header are invalid for the current user: &apos;{0}&apos;.
        /// </summary>
        internal static string CSRFMiddleware_InvalidSignature {
            get {
                return ResourceManager.GetString("CSRFMiddleware_InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JWT access_token is invalid in the request.
        /// </summary>
        internal static string CSRFMiddleware_InvalidToken {
            get {
                return ResourceManager.GetString("CSRFMiddleware_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSRF cookie is missing from the request.
        /// </summary>
        internal static string CSRFMiddleware_MissingCSRFCookieValue {
            get {
                return ResourceManager.GetString("CSRFMiddleware_MissingCSRFCookieValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSRF cookie and/or the CSRF header are invalid in the request.
        /// </summary>
        internal static string CSRFMiddleware_MissingCSRFCredentials {
            get {
                return ResourceManager.GetString("CSRFMiddleware_MissingCSRFCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSRF header is missing from the request.
        /// </summary>
        internal static string CSRFMiddleware_MissingCSRFHeaderValue {
            get {
                return ResourceManager.GetString("CSRFMiddleware_MissingCSRFHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Origin and Referer headers are missing from the request.
        /// </summary>
        internal static string CSRFMiddleware_MissingOriginAndReferer {
            get {
                return ResourceManager.GetString("CSRFMiddleware_MissingOriginAndReferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Origin of the request does not match the server.
        /// </summary>
        internal static string CSRFMiddleware_OriginMismatched {
            get {
                return ResourceManager.GetString("CSRFMiddleware_OriginMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Referer of the request does not match the server.
        /// </summary>
        internal static string CSRFMiddleware_RefererMismatched {
            get {
                return ResourceManager.GetString("CSRFMiddleware_RefererMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to AES decrypt the user ID.
        /// </summary>
        internal static string CSRFTokenPair_FailedDecryptUserId {
            get {
                return ResourceManager.GetString("CSRFTokenPair_FailedDecryptUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed HMAC authentication.
        /// </summary>
        internal static string HMACAuthenticationHandler_FailedAuthentication {
            get {
                return ResourceManager.GetString("HMACAuthenticationHandler_FailedAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a value in the &apos;{0}&apos; header of the request.
        /// </summary>
        internal static string HMACAuthenticationHandler_MissingHeader {
            get {
                return ResourceManager.GetString("HMACAuthenticationHandler_MissingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subscription level.
        /// </summary>
        internal static string RolesAndFeaturesAuthorizationHandler_HandleRequirementAsync_MissingFeature {
            get {
                return ResourceManager.GetString("RolesAndFeaturesAuthorizationHandler_HandleRequirementAsync_MissingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role.
        /// </summary>
        internal static string RolesAndFeaturesAuthorizationHandler_HandleRequirementAsync_MissingRole {
            get {
                return ResourceManager.GetString("RolesAndFeaturesAuthorizationHandler_HandleRequirementAsync_MissingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        internal static string WebApplicationExtensions_AddExceptionShielding_UnexpectedExceptionMessage {
            get {
                return ResourceManager.GetString("WebApplicationExtensions_AddExceptionShielding_UnexpectedExceptionMessage", resourceCulture);
            }
        }
    }
}
