//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Web.Hosting.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Web.Hosting.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; cannot be found in any configuration.
        /// </summary>
        internal static string AspNetConfigurationSettings_KeyNotFound {
            get {
                return ResourceManager.GetString("AspNetConfigurationSettings_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; exists, but is not a recognizable boolean value.
        /// </summary>
        internal static string AspNetConfigurationSettings_ValueNotBoolean {
            get {
                return ResourceManager.GetString("AspNetConfigurationSettings_ValueNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting &apos;{0}&apos; exists, but is not a recognizable number value.
        /// </summary>
        internal static string AspNetConfigurationSettings_ValueNotNumber {
            get {
                return ResourceManager.GetString("AspNetConfigurationSettings_ValueNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to relay new events to read model for: {0}.
        /// </summary>
        internal static string EventStreamHandlerBase_OnEventStreamStateChanged_FailedToProject {
            get {
                return ResourceManager.GetString("EventStreamHandlerBase_OnEventStreamStateChanged_FailedToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event stream {0} contains events with out of order versions..
        /// </summary>
        internal static string EventStreamHandlerBase_OutOfOrderEvents {
            get {
                return ResourceManager.GetString("EventStreamHandlerBase_OutOfOrderEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder is ready to record.
        /// </summary>
        internal static string TracingOnlyRecorder_Started {
            get {
                return ResourceManager.GetString("TracingOnlyRecorder_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be found in appsettings.json for this host.
        /// </summary>
        internal static string WebApiHostSettings_MissingSetting {
            get {
                return ResourceManager.GetString("WebApiHostSettings_MissingSetting", resourceCulture);
            }
        }
    }
}
