//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventNotificationsInfrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventNotificationsInfrastructure.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No consumer was not registered to receive notification events for subscription: {0}.
        /// </summary>
        internal static string ApiHostDomainEventingConsumerService_NotifySubscriberAsync_MissingConsumer {
            get {
                return ResourceManager.GetString("ApiHostDomainEventingConsumerService_NotifySubscriberAsync_MissingConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following consumers were found in the assemblies of the current running host, but not registered into the DI container: {0}.
        /// </summary>
        internal static string ApiHostDomainEventingConsumerService_WrapConsumers_MissingFromInjection {
            get {
                return ResourceManager.GetString("ApiHostDomainEventingConsumerService_WrapConsumers_MissingFromInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following consumers were not found in the assemblies of the current running host, and not registered at startup: {0}.
        /// </summary>
        internal static string ApiHostDomainEventingConsumerService_WrapConsumers_MissingFromRegistration {
            get {
                return ResourceManager.GetString("ApiHostDomainEventingConsumerService_WrapConsumers_MissingFromRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to notify consumer: {0}, with event: {1} ({2}).
        /// </summary>
        internal static string DomainEventingSubscriber_ConsumerFailed {
            get {
                return ResourceManager.GetString("DomainEventingSubscriber_ConsumerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Message&apos; is either missing or invalid.
        /// </summary>
        internal static string NotifyDomainEventRequestValidator_InvalidMessage {
            get {
                return ResourceManager.GetString("NotifyDomainEventRequestValidator_InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;SubscriptionName&apos; is either missing or invalid.
        /// </summary>
        internal static string NotifyDomainEventRequestValidator_InvalidSubscriptionName {
            get {
                return ResourceManager.GetString("NotifyDomainEventRequestValidator_InvalidSubscriptionName", resourceCulture);
            }
        }
    }
}
