//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Web.Api.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Web.Api.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file content type &apos;{0}&apos; is not recognized as a supported file.
        /// </summary>
        internal static string FileUploadService_DisallowedFileContent {
            get {
                return ResourceManager.GetString("FileUploadService_DisallowedFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file detected as &apos;{0}&apos; does not match the content type &apos;{1}&apos;.
        /// </summary>
        internal static string FileUploadService_InvalidContentTypeForFileType {
            get {
                return ResourceManager.GetString("FileUploadService_InvalidContentTypeForFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file name must have the same extension as the content of the file.
        /// </summary>
        internal static string FileUploadService_InvalidFileExtensionForFileType {
            get {
                return ResourceManager.GetString("FileUploadService_InvalidFileExtensionForFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file exceeds the maximum size in bytes of &apos;{0:N}B&apos;.
        /// </summary>
        internal static string FileUploadService_InvalidFileSize {
            get {
                return ResourceManager.GetString("FileUploadService_InvalidFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file has no content, and is 0B in size.
        /// </summary>
        internal static string FileUploadService_MissingContent {
            get {
                return ResourceManager.GetString("FileUploadService_MissingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no files to upload.
        /// </summary>
        internal static string FileUploadService_NoFiles {
            get {
                return ResourceManager.GetString("FileUploadService_NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported media type in response: {0}.
        /// </summary>
        internal static string JsonClient_GetTypedResponse_UnsupportedMediaType {
            get {
                return ResourceManager.GetString("JsonClient_GetTypedResponse_UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty instance of &apos;{0}&apos; could not be created, likely due to the fact that it does not have a default parameterless constructor or it has properties that require initialization at construction time. More details: {1}.
        /// </summary>
        internal static string JsonClient_TryCreateEmptyResponse_NotConstructable {
            get {
                return ResourceManager.GetString("JsonClient_TryCreateEmptyResponse_NotConstructable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-standard error.
        /// </summary>
        internal static string JsonClient_TryParseNonStandardErrors_NonStandard {
            get {
                return ResourceManager.GetString("JsonClient_TryParseNonStandardErrors_NonStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMAC authorization cannot be forwarded to another host.
        /// </summary>
        internal static string RequestExtensions_HMACAuthorization_NotSupported {
            get {
                return ResourceManager.GetString("RequestExtensions_HMACAuthorization_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request DTO type &apos;{0}&apos; is missing a &apos;{1}&apos; declared on the class.
        /// </summary>
        internal static string RequestExtensions_MissingRouteAttribute {
            get {
                return ResourceManager.GetString("RequestExtensions_MissingRouteAttribute", resourceCulture);
            }
        }
    }
}
