using Application.Interfaces.Resources;

namespace Application.Resources.Shared;

public class Identity : IIdentifiableResource
{
    public required bool HasCredentials { get; set; }

    public required bool IsMfaEnabled { get; set; }

    public required string Id { get; set; }
}

public class AuthenticateTokens
{
    public required AuthenticationToken AccessToken { get; set; }

    public required AuthenticationToken RefreshToken { get; set; }

    public required string UserId { get; set; }
}

public class ProviderAuthenticationTokens
{
    public required AuthenticationToken AccessToken { get; set; }

    public required List<AuthenticationToken> OtherTokens { get; set; }

    public required string Provider { get; set; }

    public required AuthenticationToken? RefreshToken { get; set; }
}

public class AuthenticationToken
{
    public required DateTime? ExpiresOn { get; set; }

    public required TokenType Type { get; set; }

    public required string Value { get; set; }
}

public class APIKey : IIdentifiableResource
{
    public string? Description { get; set; }

    public DateTime? ExpiresOnUtc { get; set; }

    public required string Key { get; set; }

    public required string UserId { get; set; }

    public required string Id { get; set; }
}

public class AuthToken
{
    public AuthToken(TokenType type, string value, DateTime? expiresOn)
    {
        Type = type;
        Value = value;
        ExpiresOn = expiresOn;
    }

    public DateTime? ExpiresOn { get; }

    public TokenType Type { get; }

    public string Value { get; }
}

public enum TokenType
{
    OtherToken = 0, // e.g. idToken
    AccessToken = 1, // access_token
    RefreshToken = 2 // refresh_token
}

public class SSOUser : IIdentifiableResource
{
    public required string ProviderUId { get; set; }

    public required string Id { get; set; }
}

public class PersonCredential : IIdentifiableResource
{
    public bool IsMfaEnabled { get; set; }

    public required EndUser User { get; set; }

    public required string Id { get; set; }
}

public class PersonCredentialEmailConfirmation
{
    public required string Token { get; set; }

    public required string Url { get; set; }
}

public enum CredentialMfaAuthenticatorType
{
    None = 0,
    RecoveryCodes = 1, // Recovery codes
    OobSms = 2, // Code is sent "Out of Band" in an SMS message 
    OobEmail = 3, // Code is sent "Out of Band" in an email message
    TotpAuthenticator = 4 // "Time-based One Time Password" is generated by a supported authenticator App
}

public class CredentialMfaAuthenticator : IIdentifiableResource
{
    public bool IsActive { get; set; }

    public required CredentialMfaAuthenticatorType Type { get; set; }

    public required string Id { get; set; }
}

public class CredentialMfaAuthenticatorAssociation
{
    public string? BarCodeUri { get; set; }

    public string? OobCode { get; set; }

    public List<string>? RecoveryCodes { get; set; }

    public string? Secret { get; set; }

    public required CredentialMfaAuthenticatorType Type { get; set; }
}

public class CredentialMfaAuthenticatorChallenge
{
    public string? OobCode { get; set; }

    public CredentialMfaAuthenticatorType Type { get; set; }
}

public class CredentialMfaAuthenticatorConfirmation
{
    public List<CredentialMfaAuthenticator>? Authenticators { get; set; }

    public AuthenticateTokens? Tokens { get; set; }
}

public class MachineCredential : IIdentifiableResource
{
    public required string ApiKey { get; set; }

    public required string CreatedById { get; set; }

    public string? Description { get; set; }

    public DateTime? ExpiresOnUtc { get; set; }

    public required string Id { get; set; }
}