extern alias Generators;
using System.Reflection;
using FluentAssertions;
using Generators::JetBrains.Annotations;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;
using WorkerGenerator = Generators::Tools.Generators.Workers.WorkerGenerator;

namespace Tools.Generators.Workers.UnitTests;

[UsedImplicitly]
public class WorkerGeneratorSpec
{
    private static readonly string[] AdditionalCompilationAssemblies = [];

    private static CSharpCompilation CreateCompilation(string sourceCode)
    {
        var assemblyPath = Path.GetDirectoryName(typeof(object).Assembly.Location)!;

        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(WorkerGenerator).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location)
        };
        AdditionalCompilationAssemblies.ToList()
            .ForEach(item => references.Add(MetadataReference.CreateFromFile(Path.Combine(assemblyPath, item))));
        var compilation = CSharpCompilation.Create("compilation",
            [
                CSharpSyntaxTree.ParseText(sourceCode)
            ],
            references,
            new CSharpCompilationOptions(OutputKind.ConsoleApplication));

        return compilation;
    }

    [Trait("Category", "Unit.Tooling")]
    public class GivenAConsumerClass
    {
       private GeneratorDriver _driver;

        public GivenAConsumerClass()
        {
            var generator = new WorkerGenerator();
            _driver = CSharpGeneratorDriver.Create(generator);
        }

        [Fact]
        public void WhenDefinesAConsumer_ThenGenerates()
        {
            var compilation = CreateCompilation("""
                                                using Domain.Interfaces.Entities;
                                                using Infrastructure.Eventing.Interfaces.Notifications;

                                                namespace ANamespace;

                                                public class AConsumerClass : IDomainEventNotificationConsumer
                                                {
                                                    public Task<Result<Error>> NotifyAsync(IDomainEvent domainEvent, CancellationToken cancellationToken)
                                                    {
                                                        return Task.FromResult(Result.Ok);
                                                    }
                                                }
                                                """);

            var result = Generate(compilation);

            result.Should().Be(
                """
                // <auto-generated/>
                #if REVEALGENERATEDFORAZUREFUNCTIONS
                namespace AzureFunctions.Api.WorkerHost.Functions;
                
                [JetBrains.Annotations.UsedImplicitly]
                public sealed class DeliverDomainEventTocompilationANamespaceAConsumerClass
                {
                    private readonly Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> _worker;
                
                    public DeliverDomainEventTocompilationANamespaceAConsumerClass(Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> worker)
                    {
                        _worker = worker;
                    }
                
                    [Microsoft.Azure.Functions.Worker.Function(nameof(DeliverDomainEventTocompilationANamespaceAConsumerClass))]
                    public Task Run([Microsoft.Azure.Functions.Worker.ServiceBusTrigger(Application.Interfaces.WorkerConstants.MessageBuses.Topics.DomainEvents, "ApiHost1_EndUsersInfrastructure_Notifications_OrganizationNotificationConsumer")] Application.Persistence.Shared.ReadModels.DomainEventingMessage message, Microsoft.Azure.Functions.Worker.FunctionContext context)
                    {
                        return _worker.RelayMessageOrThrowAsync("compilation", "compilation_ANamespace_AConsumerClass", message, context.CancellationToken);
                    }
                }
                #elif REVEALGENERATEDFORAWSLAMBDAS
                namespace AWSLambdas.Api.WorkerHost.Lambdas;
                
                [JetBrains.Annotations.UsedImplicitly]
                public sealed class DeliverDomainEventTocompilationANamespaceAConsumerClass
                {
                    private readonly Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> _worker;
                
                    public DeliverDomainEventTocompilationANamespaceAConsumerClass(Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> worker)
                    {
                        _worker = worker;
                    }
                
                    [Amazon.Lambda.Annotations.LambdaFunction]
                    public async Task<bool> Run(Amazon.Lambda.SQSEvents.SQSEvent sqsEvent, Amazon.Lambda.Core.ILambdaContext context)
                    {
                        return await AWSLambdas.Api.WorkerHost.Extensions.SqsEventExtensions.RelayRecordsAsync(sqsEvent, _worker, "compilation", "compilation_ANamespace_AConsumerClass", CancellationToken.None);
                    }
                }
                #endif
                
                """);
        }
        
        private string Generate(CSharpCompilation compilation)
        {
            _driver = _driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out _);
            return _driver.GetRunResult().Results[0].GeneratedSources[0].SourceText.ToString();
        }
    }
}