### Get Index.html page and extract the CSRF token from the meta tag

GET {{websitehost}}
Accept: text/html

> {%
    // Note: We parse the document as XML, not HTML. Therefore, it must be proper/valid XML!
    const doc = new DOMParser().parseFromString(response.body, "text/xml");
    const token = doc.querySelector("meta[name='csrf-token']")?.getAttribute("content");
    client.global.set("csrf_token", token);
%}

### Authenticate

POST {{websitehost}}/api/auth
Accept: application/json
Content-Type: application/json
anti-csrf-tok: {{csrf_token}}
Origin: {{websitehost}}

{
  "Username": "{{username}}",
  "Password": "{{password}}",
  "Provider" : "credentials"
}

### Who am I?

GET {{websitehost}}/api/profiles/me
Accept: application/json
anti-csrf-tok: {{csrf_token}}

{}

### Get all feature flags

GET {{websitehost}}/api/flags
Accept: application/json
X-Hub-Signature: {{hmac_signature}}
Content-Type: application/json

{ }


### Record a browser crash

POST {{websitehost}}/api/record/crash
Content-Type: application/json
anti-csrf-tok: {{csrf_token}}
Origin: {{websitehost}}

{
  "Message": "Browser crashed"
}
