
### Register a user

POST {{apihost1}}/credentials/register
Accept: application/json
Content-Type: application/json

{
  "EmailAddress": "{{username}}",
  "Password": "{{password}}",
  "FirstName" : "{{firstname}}",
  "LastName" : "{{lastname}}",
  "TermsAndConditionsAccepted": true
}

> {%
    client.global.set("user_id", response.body.person.user.id);
%}

### Get Registration Token (the one sent in an email)

GET {{apihost1}}/credentials/confirm-registration?UserId={{user_id}}
Accept: application/json

> {%
    client.global.set("registration_token", response.body.token);
%}

### Confirm registration

POST {{apihost1}}/credentials/confirm-registration
Accept: application/json
Content-Type: application/json

{
  "Token": "{{registration_token}}"
}

### Drain all events, must be done before any other operation

POST {{apihost1}}/event_notifications/drain
Accept: application/json
X-HMAC-Signature: {{hmac_signature}}
Content-Type: application/json

{ }

### Authenticate
run ./Authenticate.http