### Register and authenticate user

run ./CreateUser.http

###

GET {{apihost1}}/subscriptions/export
Accept: application/json
X-Hub-Signature: sha256=f8dbae1fc1114a368a46f762db4a5ad5417e0e1ea4bc34d7924d166621c45653
