POST {{apihost1}}/testingonly/repositories/destroy
Accept: application/json
Content-Type: application/json

{ }

###

POST {{apihost1}}/passwords/register
Accept: application/json
Content-Type: application/json

{
  "EmailAddress": "{{username}}",
  "Password": "{{password}}",
  "FirstName" : "afirstname",
  "LastName" : "alastname",
  "TermsAndConditionsAccepted": true
}

> {%
    client.global.set("user_id", response.body.credential.user.id);
%}

###

GET {{apihost1}}/passwords/confirm-registration?UserId={{user_id}}
Accept: application/json

> {%
    client.global.set("registration_token", response.body.token);
%}

###

POST {{apihost1}}/passwords/confirm-registration
Accept: application/json
Content-Type: application/json

{
  "Token": "{{registration_token}}"
}

###

POST {{apihost1}}/passwords/auth
Accept: application/json
Content-Type: application/json

{
  "Username": "{{username}}",
  "Password": "{{password}}",
  "Provider" : "credentials"
}

> {%
    client.global.set("access_token", response.body.tokens.accessToken.value);
%}

###

PUT {{apihost1}}/profiles/{{user_id}}/avatar
Accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=anything

--WebAppBoundary
Content-Disposition: form-data; name="UserId"

{{user_id}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="SuiteFiles.png"
Content-Type: image/png

< C:/Users/jezzs/OneDrive/Desktop/TestImage.png
--WebAppBoundary

> {%
    client.global.set("avatar_url", response.body.profile.avatarUrl);
%}


###

GET {{avatar_url}}
Accept: application/json
Authorization: Bearer {{access_token}}

###