using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Tools.Generators.Workers;

/// <summary>
///     A source generator for creating Azure Functions and AWS Lambdas definitions for each of the
///     <see cref="IDomainEventNotificationConsumer" /> found in the host project
/// </summary>
[Generator]
public class WorkerGenerator : ISourceGenerator
{
    private const string Filename = "DeliverDomainEvents.g.cs";

    public void Execute(GeneratorExecutionContext context)
    {
        var assemblyName = context.Compilation.AssemblyName;

        //TODO: load all IDomainEventNotificationConsumer types from all assemblies of this compilation
        var subscriptionNames = new[]
        {
            "ApiHost1_EndUsersInfrastructure_Notifications_OrganizationNotificationConsumer",
            "ApiHost1_EndUsersInfrastructure_Notifications_SubscriptionNotificationConsumer",
            "ApiHost1_OrganizationsInfrastructure_Notifications_EndUserNotificationConsumer",
            "ApiHost1_OrganizationsInfrastructure_Notifications_ImageNotificationConsumer",
            "ApiHost1_OrganizationsInfrastructure_Notifications_SubscriptionNotificationConsumer",
            "ApiHost1_SubscriptionsInfrastructure_Persistence_Notifications_OrganizationNotificationConsumer",
            "ApiHost1_UserProfilesInfrastructure_Notifications_EndUserNotificationConsumer",
            "ApiHost1_UserProfilesInfrastructure_Notifications_ImageNotificationConsumer"
        };

        var filename = $"{assemblyName}_{Filename}";
        var fileSource = BuildFile(assemblyName!, subscriptionNames);

        context.AddSource(filename, SourceText.From(fileSource, Encoding.UTF8));

        return;

        static string BuildFile(string assemblyName, string[] subscriptionNames)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("""
                               #if REVEALGENERATEDFORAZUREFUNCTIONS
                               namespace AzureFunctions.Api.WorkerHost.Functions;
                               """);
            foreach (var subscriptionName in subscriptionNames)
            {
                var className = subscriptionName.Replace("_", string.Empty);
                builder.AppendLine($$"""

                                     [JetBrains.Annotations.UsedImplicitly]
                                     public sealed class DeliverDomainEventTo{{className}}
                                     {
                                         private readonly Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> _worker;
                                     
                                         public DeliverDomainEventTo{{className}}(Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> worker)
                                         {
                                             _worker = worker;
                                         }
                                     
                                         [Microsoft.Azure.Functions.Worker.Function(nameof(DeliverDomainEventTo{{className}}))]
                                         public Task Run([Microsoft.Azure.Functions.Worker.ServiceBusTrigger(Application.Interfaces.WorkerConstants.MessageBuses.Topics.DomainEvents, "ApiHost1_EndUsersInfrastructure_Notifications_OrganizationNotificationConsumer")] Application.Persistence.Shared.ReadModels.DomainEventingMessage message, Microsoft.Azure.Functions.Worker.FunctionContext context)
                                         {
                                             return _worker.RelayMessageOrThrowAsync("{{assemblyName}}", "{{subscriptionName}}", message, context.CancellationToken);
                                         }
                                     }
                                     """);
            }

            builder.AppendLine("""
                               #elif REVEALGENERATEDFORAWSLAMBDAS
                                namespace AWSLambdas.Api.WorkerHost.Lambdas;
                               """);
            foreach (var subscriptionName in subscriptionNames)
            {
                var className = subscriptionName.Replace("_", string.Empty);
                builder.AppendLine($$"""

                                     [JetBrains.Annotations.UsedImplicitly]
                                     public sealed class DeliverDomainEventTo{{className}}
                                     {
                                         private readonly Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> _worker;
                                     
                                         public DeliverDomainEventTo{{className}}(Infrastructure.Workers.Api.IMessageBusMonitoringApiRelayWorker<Application.Persistence.Shared.ReadModels.DomainEventingMessage> worker)
                                         {
                                             _worker = worker;
                                         }
                                     
                                         [Amazon.Lambda.Annotations.LambdaFunction]
                                         public async Task<bool> Run(Amazon.Lambda.SQSEvents.SQSEvent sqsEvent, Amazon.Lambda.Core.ILambdaContext context)
                                         {
                                             return await AWSLambdas.Api.WorkerHost.Extensions.SqsEventExtensions.RelayRecordsAsync(sqsEvent, _worker, "{{assemblyName}}", "{{subscriptionName}}", CancellationToken.None);
                                         }
                                     }
                                     """);
            }

            builder.AppendLine("""
                               #endif
                               """);
            return builder.ToString();
        }
    }

    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization
    }
}