namespace Domain.Shared.Identities;

public enum MfaAuthenticatorType
{
    None = 0,
    RecoveryCodes = 1, // Recovery codes
    OobSms = 2, // Code is sent "Out of Band" in an SMS message 
    OobEmail = 3, // Code is sent "Out of Band" in an email message
    TotpAuthenticator = 4 // "Time-based One Time Password" is generated by a supported authenticator App
}