//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsDomain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarsDomain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The car cannot be deleted by anyone but it owner.
        /// </summary>
        internal static string CarRoot_NotDeletedByOwner {
            get {
                return ResourceManager.GetString("CarRoot_NotDeletedByOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manufacturer details for the car have not yet been defined.
        /// </summary>
        internal static string CarRoot_NotManufactured {
            get {
                return ResourceManager.GetString("CarRoot_NotManufactured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ownership of the car is not yet been defined.
        /// </summary>
        internal static string CarRoot_NotOwned {
            get {
                return ResourceManager.GetString("CarRoot_NotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration for the car is not yet been defined.
        /// </summary>
        internal static string CarRoot_NotRegistered {
            get {
                return ResourceManager.GetString("CarRoot_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The car cannot be taken offline in the past.
        /// </summary>
        internal static string CarRoot_OfflineInPast {
            get {
                return ResourceManager.GetString("CarRoot_OfflineInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The car cannot be reserved in the past.
        /// </summary>
        internal static string CarRoot_ReserveInPast {
            get {
                return ResourceManager.GetString("CarRoot_ReserveInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From date must not be less than {0:#}hrs from now.
        /// </summary>
        internal static string CarRoot_ScheduleMaintenanceLessThanMinimumLeadTime {
            get {
                return ResourceManager.GetString("CarRoot_ScheduleMaintenanceLessThanMinimumLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The car is not available for this time slot.
        /// </summary>
        internal static string CarRoot_Unavailable {
            get {
                return ResourceManager.GetString("CarRoot_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CausedByReference is invalid.
        /// </summary>
        internal static string CausedBy_InvalidReference {
            get {
                return ResourceManager.GetString("CausedBy_InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slot is reserved without a reservation reference.
        /// </summary>
        internal static string CausedBy_ReservationWithoutReference {
            get {
                return ResourceManager.GetString("CausedBy_ReservationWithoutReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The jurisdiction is not known.
        /// </summary>
        internal static string Jurisdiction_UnknownJurisdiction {
            get {
                return ResourceManager.GetString("Jurisdiction_UnknownJurisdiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Make of the manufacturer is unknown.
        /// </summary>
        internal static string Manufacturer_UnknownMake {
            get {
                return ResourceManager.GetString("Manufacturer_UnknownMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Model of the manufacturer is unknown.
        /// </summary>
        internal static string Manufacturer_UnknownModel {
            get {
                return ResourceManager.GetString("Manufacturer_UnknownModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is not a valid license number plate.
        /// </summary>
        internal static string NumberPlate_InvalidNumberPlate {
            get {
                return ResourceManager.GetString("NumberPlate_InvalidNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The To date must be after the From date.
        /// </summary>
        internal static string TimeSlot_FromDateBeforeToDate {
            get {
                return ResourceManager.GetString("TimeSlot_FromDateBeforeToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slot overlaps and existing slot with a different cause or reference.
        /// </summary>
        internal static string Unavailabilities_OverlappingSlot {
            get {
                return ResourceManager.GetString("Unavailabilities_OverlappingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unavailability is not configured.
        /// </summary>
        internal static string UnavailabilityEntity_NotAssigned {
            get {
                return ResourceManager.GetString("UnavailabilityEntity_NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Year of manufacturer must be between {0} and {1}.
        /// </summary>
        internal static string Year_InvalidNumber {
            get {
                return ResourceManager.GetString("Year_InvalidNumber", resourceCulture);
            }
        }
    }
}
